apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpro-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regx: /
spec:
  ingressclassName: nginx
  rules:
  - host: vprofileapp.hkhinfo.select
    http:
      paths:  
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vproapp-service
            port:
              number: 8080
